import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, isAbsolute, join, resolve } from 'node:path';
import pc from 'picocolors';
import { log } from '../util/log';

export type CiOptions = {
  readonly cwd?: string;
  /** Output path. Defaults to .github/workflows/unspaghettit.yml. */
  readonly out?: string;
  /** Run bounded model checking in the generated workflow (slower, deeper). */
  readonly modelCheck?: boolean;
  readonly dryRun?: boolean;
  readonly force?: boolean;
};

const workflowYaml = (modelCheck: boolean): string => {
  const checkCmd = modelCheck ? 'unspa check --model-check' : 'unspa check';
  return `# Generated by \`unspa ci\`. Verifies the Unspaghettit spec on every push / PR:
# scenarios as executable tests, maturity, surface reachability, spec→code drift,
# cross-feature event coherence${modelCheck ? ', and bounded model checking (invariant + liveness counterexamples)' : ''}.
# Requires the behavior model to travel with the repo — run \`unspa init --local\`
# so \`unspa/\` is committed. Tighten the gate with flags, e.g.
# \`unspa check --min-maturity 80 --fail-on-drift\`.
name: unspaghettit
on:
  push:
    branches: [main]
  pull_request:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install -g unspaghettit
      - run: ${checkCmd}
`;
};

export const runCiCommand = async (options: CiOptions = {}): Promise<number> => {
  const cwd = options.cwd ?? process.cwd();
  const yaml = workflowYaml(options.modelCheck === true);

  if (options.dryRun) {
    process.stdout.write(`${yaml}`);
    return 0;
  }

  const outPath = options.out
    ? isAbsolute(options.out)
      ? options.out
      : resolve(cwd, options.out)
    : resolve(cwd, join('.github', 'workflows', 'unspaghettit.yml'));

  if (existsSync(outPath) && options.force !== true) {
    log.err(`Refusing to overwrite existing file: ${outPath}`);
    log.dim('Re-run with --force to overwrite, or pass --out <path> to write elsewhere.');
    return 1;
  }

  const outDir = dirname(outPath);
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
  writeFileSync(outPath, yaml, 'utf8');

  log.ok(`Wrote ${pc.cyan(outPath)}`);
  log.dim('Commit it (and the unspa/ folder) so CI verifies the spec on every push / PR.');
  log.dim('The model must travel with the repo: `unspa init --local` if you haven\'t already.');
  return 0;
};
